#!/usr/bin/env bash
# Configure Nginx server so that /redirect_me is redirecting to another page.

#sudo apt update
#sudo apt install nginx -y nginx

CONFIG=" 
server {
    listen 80;
    server_name 34.239.207.57;
    location /redirect_me {
    return 301 https://www.youtube.com/watch?v=QH2-TGUlwu4
    }
}
"
echo "$CONFIG" | sudo tee /etc/nginx/sites-available/redirect_me
sudo ln -s /etc/nginx/sites-available/redirect_me /etc/nginx/sites-enabled/
sudo nginx -t
sudo service nginx reload
