#!/usr/bin/env bash
# prints the message infinity and beyond for
# unless it is killed,)

# SIGTERM
trap "echo 'I am invincible!!!'" 15


# the message forever
while true;
do
	echo "To infinity and beyond";
	sleep 2
done
